name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}    

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 14

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          cd cart
          # cp package.json /opt/server/
           npm install
           npm ci 
          
      # build and test the apps     
      - name: build
        run: |
          cd cart
        #  npm run build
         # npm run test
          
      - uses: actions/checkout@v3
      - name: Build the Docker image      
        run: cd cart; docker build . --file Dockerfile --tag robot-chop-cart:$(date +%s)

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}        

        

