name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository }}    
  IMAGE_NAME: /eugenberd/robot_shop/cart
  #PACKAGE_VERSION: hhjg

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 14

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          cd cart
          # cp package.json /opt/server/
           npm install
           npm ci 
          
      # build and test the apps     
      - name: build
        run: |
          cd cart
        #  npm run build
         # npm run test
          
      - uses: actions/checkout@v3
      - name: Build the Docker image      
        run: cd cart; docker build . --file Dockerfile --tag robot-chop-cart:$(date +%s)

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}         

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} #_${{PACKAGE_VERSION}}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: cart/Dockerfile
          context: cart
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          #image-ref: 'ghcr.io/eugenberd/robot-shop:master:${{ github.sha }}'
          image-ref: 'ghcr.io/eugenberd/robot-shop:master'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'          

        

